server:
  port: 8085

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
     discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
     routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
            
#    config:
#     enabled: true
#     uri: http://localhost:9092   
            
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

          